name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: stevebkwan/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          git_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "msftdevicesuat"
          ado_project: "Devices"
          ado_area_path: "Devices\\SW\\Drivers"
          ado_iteration_path: "Devices"
          ado_wit: "Task"
          ado_new_state: "Proposed"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100